name: build

on:
  pull_request:
    paths-ignore:
      - docs/**
  push:
    paths-ignore:
      - docs/**

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x

    - name: Run NUKE
      run: ./build.ps1
      env:
        BranchSpec: ${{ github.ref }}
        BuildNumber: ${{ github.run_number}}
        ApiKey: ${{ secrets.NUGETAPIKEY }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: ./Artifacts/*


