name: Qodana

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  qodana-scan:
    name: Qodana Scan
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2026.1
        with:
          upload-result: true
          args: --baseline qodana.sarif.json --linter qodana-dotnet --within-docker false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
