name: Documentation Checks

on:
  push:
    branches:
      - develop
    paths:
      # This ensures the check will only be run when something changes in the docs content
      - "docs/**/*" # or whatever the path to the markdown / docs files happens to be
  pull_request:
    branches:
      - develop
    paths:
      - "docs/**/*"
jobs:
  spellcheck:
    name: "Docs: Spellcheck"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        name: Check out the code
      - name: Run NUKE spell check
        run: ./build.sh --target SpellCheck
